; -------------------------------------
; Game of Life Configuration File
; -------------------------------------

; Configuration file
input_cfg = "data/level_5_zeros_h.dat"   ;

; Number of levels
levels = 10 ;

; Velocidade de exibição da saída padrão.
fps = 20 ;

; Snake lives
snake_lives = 5 ;

; Amount of food to eat
food = 7;
